Gender:
    type: entity
    table: gender
    fields:
        genderId:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: gender_id
            generator:
                strategy: IDENTITY
        label:
            type: string
            length: 50
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
