User:
    type: entity
    table: user
    fields:
        userId:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: user_id
            generator:
                strategy: IDENTITY
        username:
            type: string
            length: 50
            fixed: false
            nullable: false
        password:
            type: string
            length: 50
            fixed: false
            nullable: false
        email:
            type: string
            length: 50
            fixed: false
            nullable: false
        firstname:
            type: string
            length: 50
            fixed: false
            nullable: false
        lastname:
            type: string
            length: 50
            fixed: false
            nullable: false
        createdAt:
            type: date
            nullable: false
            column: created_at
        lastLogin:
            type: date
            nullable: false
            column: last_login
        status:
            type: boolean
            nullable: false
    manyToOne:
        userGroup:
            targetEntity: UserGroup
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_group_id:
                    referencedColumnName: user_group_id
            orphanRemoval: false
        gender:
            targetEntity: Gender
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                gender_id:
                    referencedColumnName: gender_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
